---
title: "Deliverable 3"
date: 2.8.23
output: html_notebook
---

```{r}
###INSTALLING PACKAGES
library(sf)
library(ggplot2)
```


```{r}

##SHAPE FILE
maplink = 'https://github.com/543DataVisual/Deliverable-3/raw/main/ESDIST.geojson'
mapWorld=read_sf(maplink)
mapWorld

```


```{r}
##DATA FILE
location='https://github.com/543DataVisual/Deliverable-3/raw/main/'
file='cleanedtractsfiledeliverable3.2.csv'
datalink =paste0(location,file)

mydata=read.csv(datalink)
mydata

deliverable3 <- aggregate(data=mydata,cbind(per_cap_income,total_non_english)~NAME,mean)
deliverable3

```

```{r}
###MERGING TO MAP
mapWorld_indexes=merge(mapWorld, 
                   deliverable3, 
                   by='NAME')
str(mapWorld_indexes)
```

```{r}
###MAKING MAP LAYER
baseMap= ggplot(data=mapWorld) + theme_classic() + 
         geom_sf(fill='grey', 
                 color=NA)
baseMap
```

```{r}
###DATA LAYER
numericMap= baseMap + geom_sf(data=mapWorld_indexes,
                       aes(fill=total_non_english), 
                       color=NA)
numericMap
```

```{r}
###ADDING LABELS
labels= labs(title = "Non English Speakers by Elementary School Boundary", 
               subtitle = "The City of Bellevue, Washington USA")
graph = numericMap +
  labels
graph
Legend_title="Total Non English Speakers 
(grey indicates missing)"
graph + scale_fill_gradient(name = Legend_title) +
  theme_classic()
```

