---
title: "Deliverable 3"
date: "2.8.23"
output:
  html_document:
    df_print: paged
---

```{r, message=FALSE}
#Installing packages
library(sf)
library(ggplot2)
```


```{r}
#loading in shape file
maplink = 'https://github.com/543DataVisual/Deliverable-3/raw/main/ESDIST.geojson'
mapWorld=read_sf(maplink)


```


```{r}
#loading in data file
location ='https://github.com/543DataVisual/Deliverable-3/raw/main/'
file ='cleanedtractsfiledeliverable3.2.csv'
datalink = paste0(location,file)

mydata = read.csv(datalink)

#aggregating the data to be organized by school district name with mean per capita income and total non English as the variables
deliverable3 = aggregate(data=mydata,cbind(per_cap_income,total_non_english)~NAME,mean)

```

```{r}
#merging data file to map file by school district name
mapWorld_indexes = merge(mapWorld, 
                   deliverable3, 
                   by='NAME')
```

```{r}
#creating a map layer
baseMap = ggplot(data=mapWorld) + theme_classic() + 
         geom_sf(fill='grey', 
                 color=NA)
```

```{r}
#layering the data layer on top of the map layer
numericMap = baseMap + geom_sf(data=mapWorld_indexes,
                       aes(fill=total_non_english), 
                       color=NA)
```

```{r}
#adding labels to map
labels = labs(title = "Non English Speakers by Elementary School Boundary", 
               subtitle = "The City of Bellevue, Washington USA")
graph = numericMap +
        labels
Legend_title ="Total Non English Speakers 
(grey indicates missing values)"

graph + scale_fill_gradient(name = Legend_title) +
  theme_minimal()
```

